INSERT INTO BENEFITS (ID, NAME, DESCRIPTION, IMAGE_URL) VALUES (1, 'Match Clips','Match Clips Desc', 'test');
INSERT INTO BENEFITS (ID, NAME, DESCRIPTION, IMAGE_URL) VALUES (2, 'News','News Desc', 'test');
INSERT INTO BENEFITS (ID, NAME, DESCRIPTION, IMAGE_URL) VALUES (3, 'Videos','Videos Desc', 'test');
INSERT INTO BENEFITS (ID, NAME, DESCRIPTION, IMAGE_URL) VALUES (4, 'More','Desc', 'test');

INSERT INTO PLAN (ID, NAME, DESCRIPTION, ACTUAL_PRICE, DISCOUNT_PRICE, MASTER_PLAN) VALUES (1, 'ANNUAL COMBO PLAN','Annual Combo Plan', 1199, 999 , true);
INSERT INTO PLAN (ID, NAME, DESCRIPTION, ACTUAL_PRICE, DISCOUNT_PRICE, MASTER_PLAN) VALUES (2, 'ANNUAL PLAN','Annual Plan', 750, 500 , false);
INSERT INTO PLAN (ID, NAME, DESCRIPTION, ACTUAL_PRICE, DISCOUNT_PRICE, MASTER_PLAN) VALUES (3, 'QUARTERLY PLAN','Quarterly Plan', 250, 250 , false);